name: pemohon_dukcapil_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  firebase_auth: 3.11.0
  cloud_firestore: 3.5.0
  lottie: 1.4.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
    - assets/icon/
    - assets/lottie/
  uses-material-design: true

