name: pemohon_dukcapil_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.15.4
  cupertino_icons: ^1.0.6
  date_time_picker: ^2.1.0
  device_preview: ^1.1.0
  dropdown_search: ^2.0.1
  eva_icons_flutter: ^3.1.0
  fancy_bottom_navigation: ^0.3.3
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttericon: ^2.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  horizontal_data_table: ^4.3.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  lottie: ^3.0.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  assets:
    - assets/img/
    - assets/icon/
    - assets/lottie/
    - assets/svg/
  uses-material-design: true
