name: pemohon_dukcapil_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.0.0
  firebase_auth: 4.0.1
  cloud_firestore: 4.0.1
  lottie: 1.4.3
  google_fonts: 3.0.1
  flutter_svg: 1.1.5
  fluttericon: 2.0.0
  device_preview: 1.1.0
  eva_icons_flutter: 3.1.0
  flutter_screenutil: 5.5.4
  dropdown_search: 2.0.1
  flutter_easyloading: 3.0.5
  intl: 0.17.0
  flutter_datetime_picker: 1.5.1
  image_picker: 0.8.6
  photo_view: 0.14.0
  firebase_storage: 11.0.1
  horizontal_data_table: 4.1.3
  flutter_image_compress: 1.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
    - assets/icon/
    - assets/lottie/
    - assets/svg/
  uses-material-design: true

